[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F103C8 with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F103C8 --connect-under-reset --no-location --probe 0483:3748"

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "trace"
